//.....number in the input is prime or not.........
//.......Fibonacci series..........
//........palindrome Number.......
//.........factorial...........
//........armstrong Number.......
//........reverse Number.....
//.........swap number.......
//..........chanage ascii......
//........matrix multiplication.......
///.........number of charactor in String.......
/*........patters Question......*/

public class MathsQue {
    static void primeNumber() {
        for(int i=2; i<=100; i++) {
            for(int j=2; j<i; j++) {
                if(i%j != 0) {
                    System.out.println(i);
                    break;
                }
            }
        }
    }
    public static void main(String[] args) {
        primeNumber();
    }
}


